FROM adoptopenjdk/openjdk11 AS builder	# 베이스 이미지 + 별칭
COPY gradlew .	# gradlew 복사
COPY gradle gradle	# gradle 복사
COPY build.gradle .	# build.gradle 복사
COPY settings.gradle .	# settings.gradle 복사
COPY src src	#웹어플리케이션 소스 복사
RUN chmod +x ./gradlew	#gradlew 실행 권한 부여
RUN ./gradlew bootJar	#gradlew를 통해 실행 가능한 jar파일 생성

FROM adoptopenjdk/openjdk11	#베이스 이미지 생성
COPY --from=builder build/libs/*.jar app.jar	# build이미지에서 build/libs/*.jar 파일을 app.jar로 복사

ENTRYPOINT ["java", "-jar", "/app.jar"]		# jar 파일 실행
VOLUME /tmp		#볼륨 지정